//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushWebServiceDemo.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.fsti.com", ConfigurationName="ServiceReference.IPushPortClient")]
    public interface IPushPortClient {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ShortMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeliverState))]
        void notifyShortMessageStates(DeliverState[] in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ShortMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeliverState))]
        void notifyRecivedShortMessages(ShortMessage[] in0);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="www.fsti.com")]
    public partial class DeliverState : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string deliverStateField;
        
        private long queryHandlerField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string deliverState {
            get {
                return this.deliverStateField;
            }
            set {
                this.deliverStateField = value;
                this.RaisePropertyChanged("deliverState");
            }
        }
        
        /// <remarks/>
        public long queryHandler {
            get {
                return this.queryHandlerField;
            }
            set {
                this.queryHandlerField = value;
                this.RaisePropertyChanged("queryHandler");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="www.fsti.com")]
    public partial class ShortMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string deliverTimeField;
        
        private string destPhoneNumberField;
        
        private string linkidField;
        
        private string msgContentField;
        
        private string reserveField;
        
        private string srcPhoneNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string deliverTime {
            get {
                return this.deliverTimeField;
            }
            set {
                this.deliverTimeField = value;
                this.RaisePropertyChanged("deliverTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string destPhoneNumber {
            get {
                return this.destPhoneNumberField;
            }
            set {
                this.destPhoneNumberField = value;
                this.RaisePropertyChanged("destPhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string linkid {
            get {
                return this.linkidField;
            }
            set {
                this.linkidField = value;
                this.RaisePropertyChanged("linkid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string msgContent {
            get {
                return this.msgContentField;
            }
            set {
                this.msgContentField = value;
                this.RaisePropertyChanged("msgContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string reserve {
            get {
                return this.reserveField;
            }
            set {
                this.reserveField = value;
                this.RaisePropertyChanged("reserve");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string srcPhoneNumber {
            get {
                return this.srcPhoneNumberField;
            }
            set {
                this.srcPhoneNumberField = value;
                this.RaisePropertyChanged("srcPhoneNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IPushPortClientChannel : PushWebServiceDemo.ServiceReference.IPushPortClient, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PushPortClientClient : System.ServiceModel.ClientBase<PushWebServiceDemo.ServiceReference.IPushPortClient>, PushWebServiceDemo.ServiceReference.IPushPortClient {
        
        public PushPortClientClient() {
        }
        
        public PushPortClientClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PushPortClientClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PushPortClientClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PushPortClientClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void notifyShortMessageStates(DeliverState[] in0) {
            base.Channel.notifyShortMessageStates(in0);
        }
        
        public void notifyRecivedShortMessages(ShortMessage[] in0) {
            base.Channel.notifyRecivedShortMessages(in0);
        }
    }
}
