//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。

//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果

//     重新生成代码，这些更改将会丢失。

// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=2.0.50727.42。

// 

namespace BTUCenter.Proxy.AH
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "CRMForBTUCenterSoap12SoapBinding", Namespace = "http://Interface.Customer.Besttone.cn")]
    public partial class CRMForBTUCenter : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback CRMUserAuthOperationCompleted;

        /// <remarks/>
        public CRMForBTUCenter()
        {
            this.Url = "http://10.74.23.17:9001/crmService/aservices/CRMForBTUCenterSoap12";
        }

        /// <remarks/>
        public event CRMUserAuthCompletedEventHandler CRMUserAuthCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Interface.Customer.Besttone.cn/CRMUserAuth", RequestNamespace = "http://Interface.Customer.Besttone.cn", ResponseNamespace = "http://Interface.Customer.Besttone.cn", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CRMUserAuthResult CRMUserAuth(string SystemsID, string AuthenName, string AuthenType, string CustType, string Password, string AreaCode, string ExtendField)
        {
            object[] results = this.Invoke("CRMUserAuth", new object[] {
                    SystemsID,
                    AuthenName,
                    AuthenType,
                    CustType,
                    Password,
                    AreaCode,
                    ExtendField});
            return ((CRMUserAuthResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginCRMUserAuth(string SystemsID, string AuthenName, string AuthenType, string CustType, string Password, string AreaCode, string ExtendField, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("CRMUserAuth", new object[] {
                    SystemsID,
                    AuthenName,
                    AuthenType,
                    CustType,
                    Password,
                    AreaCode,
                    ExtendField}, callback, asyncState);
        }

        /// <remarks/>
        public CRMUserAuthResult EndCRMUserAuth(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((CRMUserAuthResult)(results[0]));
        }

        /// <remarks/>
        public void CRMUserAuthAsync(string SystemsID, string AuthenName, string AuthenType, string CustType, string Password, string AreaCode, string ExtendField)
        {
            this.CRMUserAuthAsync(SystemsID, AuthenName, AuthenType, CustType, Password, AreaCode, ExtendField, null);
        }

        /// <remarks/>
        public void CRMUserAuthAsync(string SystemsID, string AuthenName, string AuthenType, string CustType, string Password, string AreaCode, string ExtendField, object userState)
        {
            if ((this.CRMUserAuthOperationCompleted == null))
            {
                this.CRMUserAuthOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCRMUserAuthOperationCompleted);
            }
            this.InvokeAsync("CRMUserAuth", new object[] {
                    SystemsID,
                    AuthenName,
                    AuthenType,
                    CustType,
                    Password,
                    AreaCode,
                    ExtendField}, this.CRMUserAuthOperationCompleted, userState);
        }

        private void OnCRMUserAuthOperationCompleted(object arg)
        {
            if ((this.CRMUserAuthCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CRMUserAuthCompleted(this, new CRMUserAuthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Interface.Customer.Besttone.cn")]
    public partial class CRMUserAuthResult
    {

        private int resultField;

        private string errorDescriptionField;

        private string extendFieldField;

        /// <remarks/>
        public int Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ErrorDescription
        {
            get
            {
                return this.errorDescriptionField;
            }
            set
            {
                this.errorDescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ExtendField
        {
            get
            {
                return this.extendFieldField;
            }
            set
            {
                this.extendFieldField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void CRMUserAuthCompletedEventHandler(object sender, CRMUserAuthCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CRMUserAuthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CRMUserAuthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public CRMUserAuthResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((CRMUserAuthResult)(this.results[0]));
            }
        }
    }
}