//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.832
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=2.0.50727.42。
// 


/// <remarks/>
namespace BTUCenter.Proxy
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "DEPServiceHttpBinding", Namespace = "http://www.chinatelecom.hub.com")]
    public partial class DEPService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback exchangeOperationCompleted;

        /// <remarks/>
        public DEPService()
        {
            this.Url = "http://localhost:8090/hnTest/services/DEPServiceHttpPort";
        }

        /// <remarks/>
        public event exchangeCompletedEventHandler exchangeCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("exchange", RequestNamespace = "http://www.chinatelecom.hub.com", ResponseNamespace = "http://www.chinatelecom.hub.com", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable = true)]
        public string exchange([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in0)
        {
            object[] results = this.Invoke("exchange", new object[] {
                    in0});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult Beginexchange(string in0, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("exchange", new object[] {
                    in0}, callback, asyncState);
        }

        /// <remarks/>
        public string Endexchange(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void exchangeAsync(string in0)
        {
            this.exchangeAsync(in0, null);
        }

        /// <remarks/>
        public void exchangeAsync(string in0, object userState)
        {
            if ((this.exchangeOperationCompleted == null))
            {
                this.exchangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexchangeOperationCompleted);
            }
            this.InvokeAsync("exchange", new object[] {
                    in0}, this.exchangeOperationCompleted, userState);
        }

        private void OnexchangeOperationCompleted(object arg)
        {
            if ((this.exchangeCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.exchangeCompleted(this, new exchangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void exchangeCompletedEventHandler(object sender, exchangeCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class exchangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal exchangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}