//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=2.0.50727.42。
// 

namespace BTUCenter.Proxy.HN
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "Projects_CthnESBAsInt_initial_EaiWebServiceSoapBinding", Namespace = "http://esb.cthneai")]
    public partial class EaiWebService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback IntegralBasicInfoQueryOperationCompleted;

        private System.Threading.SendOrPostCallback IntegralDetailInfoQueryOperationCompleted;

        private System.Threading.SendOrPostCallback ConsumeDetailQueryOperationCompleted;

        private System.Threading.SendOrPostCallback CRMUserAuthOperationCompleted;

        private System.Threading.SendOrPostCallback IntegralConsumeOperationCompleted;

        private System.Threading.SendOrPostCallback IntegralRollbackOperationCompleted;

        private System.Threading.SendOrPostCallback IntegralFreezeOperationCompleted;

        private System.Threading.SendOrPostCallback IntegralDeFreezeOperationCompleted;

        /// <remarks/>
        public EaiWebService()
        {
            //正式
            //this.Url = "http://135.125.70.65:7598/webservice/Projects_CthnESBAsInt_initial_EaiWebService";
            //测试
            this.Url = "http://135.125.70.66:13598/webservice/Projects_CthnESBAsInt_initial_EaiWebService?WSDL";
        }

        /// <remarks/>
        public event IntegralBasicInfoQueryCompletedEventHandler IntegralBasicInfoQueryCompleted;

        /// <remarks/>
        public event IntegralDetailInfoQueryCompletedEventHandler IntegralDetailInfoQueryCompleted;

        /// <remarks/>
        public event ConsumeDetailQueryCompletedEventHandler ConsumeDetailQueryCompleted;

        /// <remarks/>
        public event CRMUserAuthCompletedEventHandler CRMUserAuthCompleted;

        /// <remarks/>
        public event IntegralConsumeCompletedEventHandler IntegralConsumeCompleted;

        /// <remarks/>
        public event IntegralRollbackCompletedEventHandler IntegralRollbackCompleted;

        /// <remarks/>
        public event IntegralFreezeCompletedEventHandler IntegralFreezeCompleted;

        /// <remarks/>
        public event IntegralDeFreezeCompletedEventHandler IntegralDeFreezeCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("IntegralBasicInfoQuery", RequestNamespace = "http://esb.cthneai", ResponseNamespace = "http://esb.cthneai", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IntegralBasicInfoQueryReturn")]
        public string IntegralBasicInfoQuery(string in0)
        {
            object[] results = this.Invoke("IntegralBasicInfoQuery", new object[] {
                    in0});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginIntegralBasicInfoQuery(string in0, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("IntegralBasicInfoQuery", new object[] {
                    in0}, callback, asyncState);
        }

        /// <remarks/>
        public string EndIntegralBasicInfoQuery(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void IntegralBasicInfoQueryAsync(string in0)
        {
            this.IntegralBasicInfoQueryAsync(in0, null);
        }

        /// <remarks/>
        public void IntegralBasicInfoQueryAsync(string in0, object userState)
        {
            if ((this.IntegralBasicInfoQueryOperationCompleted == null))
            {
                this.IntegralBasicInfoQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIntegralBasicInfoQueryOperationCompleted);
            }
            this.InvokeAsync("IntegralBasicInfoQuery", new object[] {
                    in0}, this.IntegralBasicInfoQueryOperationCompleted, userState);
        }

        private void OnIntegralBasicInfoQueryOperationCompleted(object arg)
        {
            if ((this.IntegralBasicInfoQueryCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IntegralBasicInfoQueryCompleted(this, new IntegralBasicInfoQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("IntegralDetailInfoQuery", RequestNamespace = "http://esb.cthneai", ResponseNamespace = "http://esb.cthneai", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IntegralDetailInfoQueryReturn")]
        public string IntegralDetailInfoQuery(string in0)
        {
            object[] results = this.Invoke("IntegralDetailInfoQuery", new object[] {
                    in0});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginIntegralDetailInfoQuery(string in0, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("IntegralDetailInfoQuery", new object[] {
                    in0}, callback, asyncState);
        }

        /// <remarks/>
        public string EndIntegralDetailInfoQuery(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void IntegralDetailInfoQueryAsync(string in0)
        {
            this.IntegralDetailInfoQueryAsync(in0, null);
        }

        /// <remarks/>
        public void IntegralDetailInfoQueryAsync(string in0, object userState)
        {
            if ((this.IntegralDetailInfoQueryOperationCompleted == null))
            {
                this.IntegralDetailInfoQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIntegralDetailInfoQueryOperationCompleted);
            }
            this.InvokeAsync("IntegralDetailInfoQuery", new object[] {
                    in0}, this.IntegralDetailInfoQueryOperationCompleted, userState);
        }

        private void OnIntegralDetailInfoQueryOperationCompleted(object arg)
        {
            if ((this.IntegralDetailInfoQueryCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IntegralDetailInfoQueryCompleted(this, new IntegralDetailInfoQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ConsumeDetailQuery", RequestNamespace = "http://esb.cthneai", ResponseNamespace = "http://esb.cthneai", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ConsumeDetailQueryReturn")]
        public string ConsumeDetailQuery(string in0)
        {
            object[] results = this.Invoke("ConsumeDetailQuery", new object[] {
                    in0});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginConsumeDetailQuery(string in0, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ConsumeDetailQuery", new object[] {
                    in0}, callback, asyncState);
        }

        /// <remarks/>
        public string EndConsumeDetailQuery(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void ConsumeDetailQueryAsync(string in0)
        {
            this.ConsumeDetailQueryAsync(in0, null);
        }

        /// <remarks/>
        public void ConsumeDetailQueryAsync(string in0, object userState)
        {
            if ((this.ConsumeDetailQueryOperationCompleted == null))
            {
                this.ConsumeDetailQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsumeDetailQueryOperationCompleted);
            }
            this.InvokeAsync("ConsumeDetailQuery", new object[] {
                    in0}, this.ConsumeDetailQueryOperationCompleted, userState);
        }

        private void OnConsumeDetailQueryOperationCompleted(object arg)
        {
            if ((this.ConsumeDetailQueryCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsumeDetailQueryCompleted(this, new ConsumeDetailQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CRMUserAuth", RequestNamespace = "http://esb.cthneai", ResponseNamespace = "http://esb.cthneai", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("CRMUserAuthReturn")]
        public CRMUserAuthResult CRMUserAuth(string in0, string in1, string in2, string in3, string in4, string in5, string in6)
        {
            object[] results = this.Invoke("CRMUserAuth", new object[] {
                    in0,
                    in1,
                    in2,
                    in3,
                    in4,
                    in5,
                    in6});
            return ((CRMUserAuthResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginCRMUserAuth(string in0, string in1, string in2, string in3, string in4, string in5, string in6, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("CRMUserAuth", new object[] {
                    in0,
                    in1,
                    in2,
                    in3,
                    in4,
                    in5,
                    in6}, callback, asyncState);
        }

        /// <remarks/>
        public CRMUserAuthResult EndCRMUserAuth(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((CRMUserAuthResult)(results[0]));
        }

        /// <remarks/>
        public void CRMUserAuthAsync(string in0, string in1, string in2, string in3, string in4, string in5, string in6)
        {
            this.CRMUserAuthAsync(in0, in1, in2, in3, in4, in5, in6, null);
        }

        /// <remarks/>
        public void CRMUserAuthAsync(string in0, string in1, string in2, string in3, string in4, string in5, string in6, object userState)
        {
            if ((this.CRMUserAuthOperationCompleted == null))
            {
                this.CRMUserAuthOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCRMUserAuthOperationCompleted);
            }
            this.InvokeAsync("CRMUserAuth", new object[] {
                    in0,
                    in1,
                    in2,
                    in3,
                    in4,
                    in5,
                    in6}, this.CRMUserAuthOperationCompleted, userState);
        }

        private void OnCRMUserAuthOperationCompleted(object arg)
        {
            if ((this.CRMUserAuthCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CRMUserAuthCompleted(this, new CRMUserAuthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("IntegralConsume", RequestNamespace = "http://esb.cthneai", ResponseNamespace = "http://esb.cthneai", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IntegralConsumeReturn")]
        public string IntegralConsume(string in0)
        {
            object[] results = this.Invoke("IntegralConsume", new object[] {
                    in0});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginIntegralConsume(string in0, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("IntegralConsume", new object[] {
                    in0}, callback, asyncState);
        }

        /// <remarks/>
        public string EndIntegralConsume(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void IntegralConsumeAsync(string in0)
        {
            this.IntegralConsumeAsync(in0, null);
        }

        /// <remarks/>
        public void IntegralConsumeAsync(string in0, object userState)
        {
            if ((this.IntegralConsumeOperationCompleted == null))
            {
                this.IntegralConsumeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIntegralConsumeOperationCompleted);
            }
            this.InvokeAsync("IntegralConsume", new object[] {
                    in0}, this.IntegralConsumeOperationCompleted, userState);
        }

        private void OnIntegralConsumeOperationCompleted(object arg)
        {
            if ((this.IntegralConsumeCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IntegralConsumeCompleted(this, new IntegralConsumeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("IntegralRollback", RequestNamespace = "http://esb.cthneai", ResponseNamespace = "http://esb.cthneai", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IntegralRollbackReturn")]
        public string IntegralRollback(string in0)
        {
            object[] results = this.Invoke("IntegralRollback", new object[] {
                    in0});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginIntegralRollback(string in0, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("IntegralRollback", new object[] {
                    in0}, callback, asyncState);
        }

        /// <remarks/>
        public string EndIntegralRollback(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void IntegralRollbackAsync(string in0)
        {
            this.IntegralRollbackAsync(in0, null);
        }

        /// <remarks/>
        public void IntegralRollbackAsync(string in0, object userState)
        {
            if ((this.IntegralRollbackOperationCompleted == null))
            {
                this.IntegralRollbackOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIntegralRollbackOperationCompleted);
            }
            this.InvokeAsync("IntegralRollback", new object[] {
                    in0}, this.IntegralRollbackOperationCompleted, userState);
        }

        private void OnIntegralRollbackOperationCompleted(object arg)
        {
            if ((this.IntegralRollbackCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IntegralRollbackCompleted(this, new IntegralRollbackCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("IntegralFreeze", RequestNamespace = "http://esb.cthneai", ResponseNamespace = "http://esb.cthneai", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IntegralFreezeReturn")]
        public string IntegralFreeze(string in0)
        {
            object[] results = this.Invoke("IntegralFreeze", new object[] {
                    in0});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginIntegralFreeze(string in0, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("IntegralFreeze", new object[] {
                    in0}, callback, asyncState);
        }

        /// <remarks/>
        public string EndIntegralFreeze(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void IntegralFreezeAsync(string in0)
        {
            this.IntegralFreezeAsync(in0, null);
        }

        /// <remarks/>
        public void IntegralFreezeAsync(string in0, object userState)
        {
            if ((this.IntegralFreezeOperationCompleted == null))
            {
                this.IntegralFreezeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIntegralFreezeOperationCompleted);
            }
            this.InvokeAsync("IntegralFreeze", new object[] {
                    in0}, this.IntegralFreezeOperationCompleted, userState);
        }

        private void OnIntegralFreezeOperationCompleted(object arg)
        {
            if ((this.IntegralFreezeCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IntegralFreezeCompleted(this, new IntegralFreezeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("IntegralDeFreeze", RequestNamespace = "http://esb.cthneai", ResponseNamespace = "http://esb.cthneai", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IntegralDeFreezeReturn")]
        public string IntegralDeFreeze(string in0)
        {
            object[] results = this.Invoke("IntegralDeFreeze", new object[] {
                    in0});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginIntegralDeFreeze(string in0, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("IntegralDeFreeze", new object[] {
                    in0}, callback, asyncState);
        }

        /// <remarks/>
        public string EndIntegralDeFreeze(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void IntegralDeFreezeAsync(string in0)
        {
            this.IntegralDeFreezeAsync(in0, null);
        }

        /// <remarks/>
        public void IntegralDeFreezeAsync(string in0, object userState)
        {
            if ((this.IntegralDeFreezeOperationCompleted == null))
            {
                this.IntegralDeFreezeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIntegralDeFreezeOperationCompleted);
            }
            this.InvokeAsync("IntegralDeFreeze", new object[] {
                    in0}, this.IntegralDeFreezeOperationCompleted, userState);
        }

        private void OnIntegralDeFreezeOperationCompleted(object arg)
        {
            if ((this.IntegralDeFreezeCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IntegralDeFreezeCompleted(this, new IntegralDeFreezeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://esb.cthneai")]
    public partial class CRMUserAuthResult
    {

        private string errorDescriptionField;

        private string extendFieldField;

        private int resultField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string errorDescription
        {
            get
            {
                return this.errorDescriptionField;
            }
            set
            {
                this.errorDescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string extendField
        {
            get
            {
                return this.extendFieldField;
            }
            set
            {
                this.extendFieldField = value;
            }
        }

        /// <remarks/>
        public int result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void IntegralBasicInfoQueryCompletedEventHandler(object sender, IntegralBasicInfoQueryCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IntegralBasicInfoQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal IntegralBasicInfoQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void IntegralDetailInfoQueryCompletedEventHandler(object sender, IntegralDetailInfoQueryCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IntegralDetailInfoQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal IntegralDetailInfoQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void ConsumeDetailQueryCompletedEventHandler(object sender, ConsumeDetailQueryCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsumeDetailQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ConsumeDetailQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void CRMUserAuthCompletedEventHandler(object sender, CRMUserAuthCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CRMUserAuthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CRMUserAuthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public CRMUserAuthResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((CRMUserAuthResult)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void IntegralConsumeCompletedEventHandler(object sender, IntegralConsumeCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IntegralConsumeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal IntegralConsumeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void IntegralRollbackCompletedEventHandler(object sender, IntegralRollbackCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IntegralRollbackCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal IntegralRollbackCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void IntegralFreezeCompletedEventHandler(object sender, IntegralFreezeCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IntegralFreezeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal IntegralFreezeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void IntegralDeFreezeCompletedEventHandler(object sender, IntegralDeFreezeCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IntegralDeFreezeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal IntegralDeFreezeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}