//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5472
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
namespace BTUCenter.Proxy
{
    // 
    // 此源代码由 wsdl 自动生成, Version=2.0.50727.42。
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Web.Services.WebServiceAttribute(Namespace = "www.fsti.com")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "PushPortClientSoapBinding", Namespace = "www.fsti.com")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ShortMessage))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(DeliverState))]
    public abstract partial class IPushPortClientService : System.Web.Services.WebService
    {

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "www.fsti.com", ResponseNamespace = "www.fsti.com")]
        public abstract void notifyShortMessageStates(DeliverState[] in0);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "www.fsti.com", ResponseNamespace = "www.fsti.com")]
        public abstract void notifyRecivedShortMessages(ShortMessage[] in0);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "www.fsti.com")]
    public partial class DeliverState
    {

        private string deliverStateField;

        private long queryHandlerField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string deliverState
        {
            get
            {
                return this.deliverStateField;
            }
            set
            {
                this.deliverStateField = value;
            }
        }

        /// <remarks/>
        public long queryHandler
        {
            get
            {
                return this.queryHandlerField;
            }
            set
            {
                this.queryHandlerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "www.fsti.com")]
    public partial class ShortMessage
    {

        private string deliverTimeField;

        private string destPhoneNumberField;

        private string linkidField;

        private string msgContentField;

        private string reserveField;

        private string srcPhoneNumberField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string deliverTime
        {
            get
            {
                return this.deliverTimeField;
            }
            set
            {
                this.deliverTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string destPhoneNumber
        {
            get
            {
                return this.destPhoneNumberField;
            }
            set
            {
                this.destPhoneNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string linkid
        {
            get
            {
                return this.linkidField;
            }
            set
            {
                this.linkidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string msgContent
        {
            get
            {
                return this.msgContentField;
            }
            set
            {
                this.msgContentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string reserve
        {
            get
            {
                return this.reserveField;
            }
            set
            {
                this.reserveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string srcPhoneNumber
        {
            get
            {
                return this.srcPhoneNumberField;
            }
            set
            {
                this.srcPhoneNumberField = value;
            }
        }
    }
}