//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=2.0.50727.42。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="UaServerBinding", Namespace="http://www.mbossuac.com.cn/ua")]
public partial class UaService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback authReqOperationCompleted;
    
    private System.Threading.SendOrPostCallback SelectAssertionOperationCompleted;
    
    /// <remarks/>
    public UaService() {
        this.Url = "http://localhost:8080/UaService/UAAuth";
    }
    
    /// <remarks/>
    public event authReqCompletedEventHandler authReqCompleted;
    
    /// <remarks/>
    public event SelectAssertionCompletedEventHandler SelectAssertionCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("authReq", RequestNamespace="http://www.mbossuac.com.cn/ua", ResponseNamespace="http://www.mbossuac.com.cn/ua", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string authReq([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string request) {
        object[] results = this.Invoke("authReq", new object[] {
                    request});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginauthReq(string request, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("authReq", new object[] {
                    request}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndauthReq(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void authReqAsync(string request) {
        this.authReqAsync(request, null);
    }
    
    /// <remarks/>
    public void authReqAsync(string request, object userState) {
        if ((this.authReqOperationCompleted == null)) {
            this.authReqOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthReqOperationCompleted);
        }
        this.InvokeAsync("authReq", new object[] {
                    request}, this.authReqOperationCompleted, userState);
    }
    
    private void OnauthReqOperationCompleted(object arg) {
        if ((this.authReqCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.authReqCompleted(this, new authReqCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SelectAssertion", RequestNamespace="http://www.mbossuac.com.cn/ua", ResponseNamespace="http://www.mbossuac.com.cn/ua", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SelectAssertion([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string request) {
        object[] results = this.Invoke("SelectAssertion", new object[] {
                    request});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSelectAssertion(string request, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SelectAssertion", new object[] {
                    request}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndSelectAssertion(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void SelectAssertionAsync(string request) {
        this.SelectAssertionAsync(request, null);
    }
    
    /// <remarks/>
    public void SelectAssertionAsync(string request, object userState) {
        if ((this.SelectAssertionOperationCompleted == null)) {
            this.SelectAssertionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectAssertionOperationCompleted);
        }
        this.InvokeAsync("SelectAssertion", new object[] {
                    request}, this.SelectAssertionOperationCompleted, userState);
    }
    
    private void OnSelectAssertionOperationCompleted(object arg) {
        if ((this.SelectAssertionCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SelectAssertionCompleted(this, new SelectAssertionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void authReqCompletedEventHandler(object sender, authReqCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class authReqCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal authReqCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void SelectAssertionCompletedEventHandler(object sender, SelectAssertionCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SelectAssertionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SelectAssertionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
