//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2407
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl, Version=1.1.4322.2407 自动生成。
// 
using System.Diagnostics;
using System.Xml.Serialization;
using System;
using System.Web.Services.Protocols;
using System.ComponentModel;
using System.Web.Services;


/// <remarks/>
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "CRMForBTUCenterSoapSoapBinding", Namespace = "http://Interface.Customer.Besttone.cn")]
public class testSoap : System.Web.Services.Protocols.SoapHttpClientProtocol
{

    /// <remarks/>
    public testSoap()
    {
        this.Url = "http://bksvc-test.besttone.com.cn/yuanfeng/services/CRMForBTUCenterSoap";
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Interface.Customer.Besttone.cn/CRMUserAuth", RequestNamespace = "http://Interface.Customer.Besttone.cn", ResponseNamespace = "http://Interface.Customer.Besttone.cn", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public testCRMUserAuthResult CRMUserAuth(string SystemsID, string AuthenName, string AuthenType, string CustType, string Password, string AreaCode, string ExtendField)
    {
        object[] results = this.Invoke("CRMUserAuth", new object[] {
                    SystemsID,
                    AuthenName,
                    AuthenType,
                    CustType,
                    Password,
                    AreaCode,
                    ExtendField});
        return ((testCRMUserAuthResult)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginCRMUserAuth(string SystemsID, string AuthenName, string AuthenType, string CustType, string Password, string AreaCode, string ExtendField, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("CRMUserAuth", new object[] {
                    SystemsID,
                    AuthenName,
                    AuthenType,
                    CustType,
                    Password,
                    AreaCode,
                    ExtendField}, callback, asyncState);
    }

    /// <remarks/>
    public testCRMUserAuthResult EndCRMUserAuth(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((testCRMUserAuthResult)(results[0]));
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Interface.Customer.Besttone.cn")]
public class testCRMUserAuthResult
{

    /// <remarks/>
    public int Result;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ErrorDescription;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ExtendField;
}
